### ISSUE TITLE
Error in retraining

### ISSUE THREAD

**Issue by EnricoGiordano1992** [SmartSearch/Audio-Scene-Analysis#1]
Hi, I'm trying to retrain the models of this project, but, using the example file, I have this error:
```
$python3 smart/audio/train.py samples/Samples_list.txt
Cannot open file /tmp/tmppoz7q34w/ubm.dmfcc!
Traceback (most recent call last):
  File "smart/audio/train.py", line 51, in <module>
    sys.exit(main(sys.argv))
  File "smart/audio/train.py", line 48, in main
    trn.createAllGmms(args.modelDir, fd)
  File "/RESEARCH/Audio-Scene-Analysis/smart/audio/AudioClassifier.py", line 139, in createAllGmms
    self.createUbm(gmmFile, filesData)
  File "/RESEARCH/Audio-Scene-Analysis/smart/audio/AudioClassifier.py", line 98, in createUbm
    self.do(cmd)
  File "/RESEARCH/Audio-Scene-Analysis/smart/audio/AudioClassifier.py", line 51, in do
    raise TrainException("rc={0}".format(rc))
smart.audio.AudioClassifier.TrainException: TrainException= rc=512
```

What does it mean?

Thanks

**Comment by zvik** [comment]
Seems that the tool can't create one of its data files. Maybe you run out of disk space.

**Comment by EnricoGiordano1992** [comment]
I have 400GB of free space, so I think that it is not the problem...

**Comment by zvik** [comment]
Try using -vv to get more logging info to see what happens

**Comment by EnricoGiordano1992** [comment]
This is the verbose output:
```
INFO:root:loadFilesList: loading samples/Samples_list.txt
INFO:root:createUbm: creating /tmp/tmpo07o7588/ubm.dmfcc
INFO:root:createUbm: building GMM model
DEBUG:root:DO: /usr/local/bin/gmm -l 48 -m 16 /tmp/tmpo07o7588/ubm.dmfcc > ./models/ubm.gmm
Cannot open file /tmp/tmpo07o7588/ubm.dmfcc!
Traceback (most recent call last):
  File "smart/audio/train.py", line 51, in <module>
    sys.exit(main(sys.argv))
  File "smart/audio/train.py", line 48, in main
    trn.createAllGmms(args.modelDir, fd)
  File "/RESEARCH/Audio-Scene-Analysis/smart/audio/AudioClassifier.py", line 139, in createAllGmms
    self.createUbm(gmmFile, filesData)
  File "/RESEARCH/Audio-Scene-Analysis/smart/audio/AudioClassifier.py", line 98, in createUbm
    self.do(cmd)
  File "/RESEARCH/Audio-Scene-Analysis/smart/audio/AudioClassifier.py", line 51, in do
    raise TrainException("rc={0}".format(rc))
smart.audio.AudioClassifier.TrainException: TrainException= rc=512
```

**Comment by zvik** [comment]
It didn't seem to process any audio files. It might be because your file list is either empty or not in the correct format.

**Comment by EnricoGiordano1992** [comment]
I've just use your training file, as is from the github.

**Comment by EnricoGiordano1992** [comment]
I see that there is a problem with this function (in AudioClassifier.py):

```
 loadFilesData(self, listFile)
```

because it returns empty filesData variable. It seems that listFile variable is not empty (is a string derived by program argument, and the file exists), but this function is stuck in this part of code:

```
                if len(files)!=2:
                    continue
```
I'm not sure how it works, any suggestions?
